version: '3.8'

services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    hostname: nginx
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www:/var/www
      - /etc/ssl/ssl:/etc/ssl/ssl
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php7.4
      - php8.1
      - mysql
    networks:
      dnmp:
        ipv4_address: 172.17.0.10

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lbdj147369
    networks:
      dnmp:
        ipv4_address: 172.17.0.20

  php7.4:
    build:
      context: ./php7.4
      dockerfile: Dockerfile
    container_name: php7.4
    hostname: php7
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    volumes:
      - /var/www:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      dnmp:
        ipv4_address: 172.17.0.30

  php8.1:
    build:
      context: ./php8.1
      dockerfile: Dockerfile
    container_name: php8.1
    hostname: php8
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    volumes:
      - /var/www:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      dnmp:
        ipv4_address: 172.17.0.40

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - /data:/data
    networks:
      dnmp:
        ipv4_address: 172.17.0.50

networks:
  dnmp:
    ipam:
      config:
        - subnet: 172.17.0.0/16
