version: '3.8'

services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    hostname: nginx
    environment:
      - TZ=${TZ}
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_SITE}:/var/www
      - ${PATH_SSL}:/etc/nginx/ssl
      - ${PATH_SITE_CONF}:/etc/nginx/conf.d
    networks:
      dnmp:
        ipv4_address: 172.18.0.10

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    privileged: true
    restart: always
    volumes:
      - ${PATH_MYSQL}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    networks:
      dnmp:
        ipv4_address: 172.18.0.20

  php7.4:
    build:
      context: ./php7.4
      dockerfile: Dockerfile
    container_name: php7.4
    hostname: php7
    environment:
      - TZ=${TZ}
    privileged: true
    restart: always
    volumes:
      - ${PATH_SITE}:/var/www
    networks:
      dnmp:
        ipv4_address: 172.18.0.30

  php8.1:
    build:
      context: ./php8.1
      dockerfile: Dockerfile
    container_name: php8.1
    hostname: php8
    environment:
      - TZ=${TZ}
    privileged: true
    restart: always
    volumes:
      - ${PATH_SITE}:/var/www
    networks:
      dnmp:
        ipv4_address: 172.18.0.40

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    environment:
      - TZ=${TZ}
    privileged: true
    restart: always
    volumes:
      - ${PATH_REDIS}:/data
    networks:
      dnmp:
        ipv4_address: 172.18.0.50

networks:
  dnmp:
    ipam:
      config:
        - subnet: 172.18.0.0/16
